server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.3.119:3306/habit_tracker?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: habit_user
    password: habit_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # dev: update; prod: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
